export const matches = [
  {
      "id": 1,
      "squad_id": 1,
      "season_id": 1,
      "competition_id": 1,
      "date_time": "2022-03-13T00:01:22.682Z",
      "opposition": "Naas",
      "at_home": true,
      "goals_for": 2,
      "goals_against": 0,
      "manager_notes": null,
      "createdAt": "2022-03-13T00:01:22.682Z",
      "updatedAt": "2022-03-13T00:01:22.682Z",
      "CompetitionId": 1,
      "SeasonId": 1,
      "SquadId": 1,
      "Competition": {
          "id": 1,
          "name": "League",
          "competitive": true,
          "createdAt": "2022-03-13T00:01:22.678Z",
          "updatedAt": "2022-03-13T00:01:22.678Z"
      },
      "Players": [
          {
              "id": 1,
              "first_name": "Dylan",
              "last_name": "Connolly",
              "nickname": "Dildo",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.644Z",
              "updatedAt": "2022-03-13T00:01:22.644Z",
              "PlayerMatch": {
                  "player_id": 1,
                  "match_id": 1,
                  "goals_scored": 1,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": true,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6.7,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.686Z",
                  "updatedAt": "2022-03-13T00:01:22.686Z",
                  "MatchId": 1,
                  "PlayerId": 1
              }
          },
          {
              "id": 2,
              "first_name": "Some",
              "last_name": "Keeper",
              "nickname": "Cat",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.657Z",
              "updatedAt": "2022-03-13T00:01:22.657Z",
              "PlayerMatch": {
                  "player_id": 2,
                  "match_id": 1,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 9,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.688Z",
                  "updatedAt": "2022-03-13T00:01:22.688Z",
                  "MatchId": 1,
                  "PlayerId": 2
              }
          },
          {
              "id": 3,
              "first_name": "Gary",
              "last_name": "Scully",
              "nickname": null,
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.663Z",
              "updatedAt": "2022-03-13T00:01:22.663Z",
              "PlayerMatch": {
                  "player_id": 3,
                  "match_id": 1,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6.7,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.690Z",
                  "updatedAt": "2022-03-13T00:01:22.690Z",
                  "MatchId": 1,
                  "PlayerId": 3
              }
          }
      ]
  },
  {
      "id": 2,
      "squad_id": 1,
      "season_id": 1,
      "competition_id": 1,
      "date_time": "2022-03-13T00:01:22.691Z",
      "opposition": "Athy Town",
      "at_home": false,
      "goals_for": 3,
      "goals_against": 4,
      "manager_notes": null,
      "createdAt": "2022-03-13T00:01:22.691Z",
      "updatedAt": "2022-03-13T00:01:22.691Z",
      "CompetitionId": 1,
      "SeasonId": 1,
      "SquadId": 1,
      "Competition": {
          "id": 1,
          "name": "League",
          "competitive": true,
          "createdAt": "2022-03-13T00:01:22.678Z",
          "updatedAt": "2022-03-13T00:01:22.678Z"
      },
      "Players": [
          {
              "id": 1,
              "first_name": "Dylan",
              "last_name": "Connolly",
              "nickname": "Dildo",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.644Z",
              "updatedAt": "2022-03-13T00:01:22.644Z",
              "PlayerMatch": {
                  "player_id": 1,
                  "match_id": 2,
                  "goals_scored": 2,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 7,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.693Z",
                  "updatedAt": "2022-03-13T00:01:22.693Z",
                  "MatchId": 2,
                  "PlayerId": 1
              }
          },
          {
              "id": 2,
              "first_name": "Some",
              "last_name": "Keeper",
              "nickname": "Cat",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.657Z",
              "updatedAt": "2022-03-13T00:01:22.657Z",
              "PlayerMatch": {
                  "player_id": 2,
                  "match_id": 2,
                  "goals_scored": 1,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": true,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 8,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.695Z",
                  "updatedAt": "2022-03-13T00:01:22.695Z",
                  "MatchId": 2,
                  "PlayerId": 2
              }
          },
          {
              "id": 3,
              "first_name": "Gary",
              "last_name": "Scully",
              "nickname": null,
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.663Z",
              "updatedAt": "2022-03-13T00:01:22.663Z",
              "PlayerMatch": {
                  "player_id": 3,
                  "match_id": 2,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.697Z",
                  "updatedAt": "2022-03-13T00:01:22.697Z",
                  "MatchId": 2,
                  "PlayerId": 3
              }
          }
      ]
  },
  {
      "id": 3,
      "squad_id": 1,
      "season_id": 1,
      "competition_id": 2,
      "date_time": "2022-03-13T00:01:22.698Z",
      "opposition": "Rathangan",
      "at_home": true,
      "goals_for": 3,
      "goals_against": 2,
      "manager_notes": null,
      "createdAt": "2022-03-13T00:01:22.698Z",
      "updatedAt": "2022-03-13T00:01:22.698Z",
      "CompetitionId": 2,
      "SeasonId": 1,
      "SquadId": 1,
      "Competition": {
          "id": 2,
          "name": "Senior Cup",
          "competitive": true,
          "createdAt": "2022-03-13T00:01:22.680Z",
          "updatedAt": "2022-03-13T00:01:22.680Z"
      },
      "Players": [
          {
              "id": 1,
              "first_name": "Dylan",
              "last_name": "Connolly",
              "nickname": "Dildo",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.644Z",
              "updatedAt": "2022-03-13T00:01:22.644Z",
              "PlayerMatch": {
                  "player_id": 1,
                  "match_id": 3,
                  "goals_scored": 2,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 4,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.701Z",
                  "updatedAt": "2022-03-13T00:01:22.701Z",
                  "MatchId": 3,
                  "PlayerId": 1
              }
          },
          {
              "id": 2,
              "first_name": "Some",
              "last_name": "Keeper",
              "nickname": "Cat",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.657Z",
              "updatedAt": "2022-03-13T00:01:22.657Z",
              "PlayerMatch": {
                  "player_id": 2,
                  "match_id": 3,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": true,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 8,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.703Z",
                  "updatedAt": "2022-03-13T00:01:22.703Z",
                  "MatchId": 3,
                  "PlayerId": 2
              }
          },
          {
              "id": 3,
              "first_name": "Gary",
              "last_name": "Scully",
              "nickname": null,
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.663Z",
              "updatedAt": "2022-03-13T00:01:22.663Z",
              "PlayerMatch": {
                  "player_id": 3,
                  "match_id": 3,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 7.2,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.705Z",
                  "updatedAt": "2022-03-13T00:01:22.705Z",
                  "MatchId": 3,
                  "PlayerId": 3
              }
          }
      ]
  },
  {
      "id": 4,
      "squad_id": 2,
      "season_id": 2,
      "competition_id": 1,
      "date_time": "2022-03-13T00:01:22.706Z",
      "opposition": "Sallins",
      "at_home": true,
      "goals_for": 3,
      "goals_against": 2,
      "manager_notes": null,
      "createdAt": "2022-03-13T00:01:22.706Z",
      "updatedAt": "2022-03-13T00:01:22.706Z",
      "CompetitionId": 1,
      "SeasonId": 2,
      "SquadId": 2,
      "Competition": {
          "id": 1,
          "name": "League",
          "competitive": true,
          "createdAt": "2022-03-13T00:01:22.678Z",
          "updatedAt": "2022-03-13T00:01:22.678Z"
      },
      "Players": [
          {
              "id": 2,
              "first_name": "Some",
              "last_name": "Keeper",
              "nickname": "Cat",
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.657Z",
              "updatedAt": "2022-03-13T00:01:22.657Z",
              "PlayerMatch": {
                  "player_id": 2,
                  "match_id": 4,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": true,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6.5,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.708Z",
                  "updatedAt": "2022-03-13T00:01:22.708Z",
                  "MatchId": 4,
                  "PlayerId": 2
              }
          },
          {
              "id": 4,
              "first_name": "Adam",
              "last_name": "Stack",
              "nickname": null,
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.668Z",
              "updatedAt": "2022-03-13T00:01:22.668Z",
              "PlayerMatch": {
                  "player_id": 4,
                  "match_id": 4,
                  "goals_scored": 0,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": false,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6.5,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-13T00:01:22.709Z",
                  "updatedAt": "2022-03-13T00:01:22.709Z",
                  "MatchId": 4,
                  "PlayerId": 4
              }
          }
      ]
  },
  {
      "id": 6,
      "squad_id": 1,
      "season_id": 1,
      "competition_id": 3,
      "date_time": "2022-03-14T00:18:56.549Z",
      "opposition": "Sallins",
      "at_home": true,
      "goals_for": 2,
      "goals_against": 0,
      "manager_notes": null,
      "createdAt": "2022-03-14T00:18:56.550Z",
      "updatedAt": "2022-03-14T00:18:56.550Z",
      "CompetitionId": 3,
      "SeasonId": 1,
      "SquadId": 1,
      "Competition": {
          "id": 3,
          "name": "Friendly",
          "competitive": false,
          "createdAt": "2022-03-13T00:01:22.681Z",
          "updatedAt": "2022-03-13T00:01:22.681Z"
      },
      "Players": [
          {
              "id": 3,
              "first_name": "Gary",
              "last_name": "Scully",
              "nickname": null,
              "dob": "2022-03-13",
              "ph_number": null,
              "email": null,
              "active": true,
              "createdAt": "2022-03-13T00:01:22.663Z",
              "updatedAt": "2022-03-13T00:01:22.663Z",
              "PlayerMatch": {
                  "player_id": 3,
                  "match_id": 6,
                  "goals_scored": 1,
                  "assists": 0,
                  "clean_sheet": true,
                  "mom": true,
                  "started": false,
                  "on_as_sub": false,
                  "unused_sub": false,
                  "mins_played": 0,
                  "manager_player_rating": 6.7,
                  "paid_match_fee": false,
                  "manager_notes": null,
                  "createdAt": "2022-03-14T00:18:56.610Z",
                  "updatedAt": "2022-03-14T00:18:56.610Z",
                  "MatchId": 6,
                  "PlayerId": 3
              }
          }
      ]
  },
  {
      "id": 5,
      "squad_id": 1,
      "season_id": 1,
      "competition_id": 1,
      "date_time": "2022-03-13T22:40:20.238Z",
      "opposition": "Kilcock",
      "at_home": true,
      "goals_for": 2,
      "goals_against": 0,
      "manager_notes": null,
      "createdAt": "2022-03-13T22:40:20.240Z",
      "updatedAt": "2022-03-13T22:40:20.240Z",
      "CompetitionId": 1,
      "SeasonId": 1,
      "SquadId": 1,
      "Competition": {
          "id": 1,
          "name": "League",
          "competitive": true,
          "createdAt": "2022-03-13T00:01:22.678Z",
          "updatedAt": "2022-03-13T00:01:22.678Z"
      },
      "Players": []
  }
]